### ISSUE TITLE
Node16 instead of Node12

### ISSUE THREAD

**Issue by LangLangBart** [korelstar/xmllint-problem-matcher#6]
- [GitHub Blog GitHub Actions: All Actions will begin running on Node16 instead of Node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
> we are adding a warning into workflows which contain Actions running on Node 12.

Getting some warnings on a repo:
- https://github.com/LangLangBart/boonGUI/actions/runs/3244257909

**Comment by korelstar** [comment]
Thanks for this hint! It's fixed in v1.1 :smile:
